# theme = "catppuccin_mocha"
theme = "gruvbox"

[editor]
line-number = "relative"
bufferline = "always"
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position-percentage", "file-encoding", "file-line-ending", "file-type"]

[keys.insert]
j = { k = "normal_mode" } # Exits insert mode

[keys.normal.space]
e = ":sh zellij run -c -- broot"
[keys.normal.space.t]
a = ":sh zellij run -- python -m unittest discover -s src" # Run all tests
c = ":sh cd src && zellij run -- python -m unittest $1" # Run tests in current file
