[[language]]
name = "python"

[language.config.pylsp.plugins]
flake8 = {enabled = false}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
rope_autoimport = {enabled = true}
isort = {enabled = true}
ruff = { enabled = true, lineLength = 80}

# Formatter config
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true